# Generated by Django 5.2.8 on 2025-11-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_product_image_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('physical', 'Физический товар'), ('digital', 'Цифровой товар'), ('service', 'Услуга')], default='physical', max_length=20, verbose_name='Тип товара'),
        ),
    ]
