# Generated by Django 5.2.8 on 2025-12-16 16:19

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_order_tag_orderitem_order_products_productdetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.Product.product_image_upload_to, verbose_name='Изображение'),
        ),
    ]
